# Generated by Django 5.0.7 on 2024-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='mode',
            field=models.TextField(default='Public', max_length=10),
        ),
    ]
