# Generated by Django 5.0.7 on 2024-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_snippet_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='mode',
            field=models.TextField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10),
        ),
    ]
