# Generated by Django 5.0.7 on 2024-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_snippet_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='mode',
            field=models.TextField(choices=[('public', 'public'), ('private', 'private')], max_length=10),
        ),
    ]
